apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-web-ingress
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - prod.127.0.0.1.nip.io  # ğŸ”¥ ä¿®æ”¹åŸŸå
      secretName: prod-my-web-tls # è¯ä¹¦åå­—æœ€å¥½ä¹Ÿæ”¹ä¸€ä¸‹ï¼Œé˜²æ­¢å†²çª
  rules:
    - host: prod.127.0.0.1.nip.io # ğŸ”¥ ä¿®æ”¹åŸŸå
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-web
                port:
                  number: 80